apiVersion: v1
kind: Namespace
metadata:
  name: $namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: $namespace
  name: $deployment_name
spec:
  replicas: $replicas
  selector:
    matchLabels:
      app: $deployment_name
  template:
    metadata:
      labels:
        app: $deployment_name
    spec:
      containers:
      - name: rag-tool-container
        image: python:3.8-slim
        ports:
        - containerPort: 8000
        env:
        - name: RAG_USE_AUTH
          value: "$rag_use_auth"
        - name: RAG_MASTER_KEY
          value: "$rag_master_key"
        command: ["/bin/sh", "-c"]
        args:
        - |
          apt-get update && apt-get install -y git
          git clone https://github.com/kalavai-net/tool_library.git /app/tool_library
          cd /app/tool_library
          git checkout feature/updates
          pip install fastapi uvicorn
          cd tool_library/example_tools/rag
          pip install -r requirements.txt
          uvicorn api:app --host 0.0.0.0 --port 8000
        resources:
          limits:
            cpu: $cpu_limits
            memory: $memory_limits
          requests:
            cpu: $cpu_requests
            memory: $memory_requests
        volumeMounts:
        - name: ${deployment_name}-volume
          mountPath: "/tool"
      restartPolicy: Always
      volumes:
      - name: ${deployment_name}-volume
---
apiVersion: v1
kind: Service
metadata:
  name: ${deployment_name}-service
  namespace: $namespace
  labels:
    app: $deployment_name
spec:
  selector:
    app: $deployment_name
  ports:
    - name: http
      port: 8000
  type: NodePort
