apiVersion: apps/v1
kind: Deployment
metadata:
  name: $deployment_name
  namespace: $namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: $deployment_name
  template:
    metadata:
      labels:
        app: $deployment_name
    spec:
      containers:
      - name: $deployment_name-container
        image: localai/localai:v2.7.0-ffmpeg-core
        ports:
        - containerPort: 8080
        args: ["phi-2"] # we should param this 
        resources:
          limits:
            cpu: $cpu_limits
            memory: $memory_limits
          requests:
            cpu: $cpu_requests
            memory: $memory_requests
        volumeMounts:
        - name: $deployment_name-storage
          mountPath: "/model"
      restartPolicy: Always
      volumes:
      - name: $deployment_name-storage
---
apiVersion: v1
kind: Service
metadata:
  name: $deployment_name-service
  namespace: $namespace
spec:
  selector:
    app: $deployment_name
  ports:
    - name: http
      port: 8080
  type: NodePort
