apiVersion: v1
kind: Namespace
metadata:
  name: demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmarkmodel
  namespace: demo
  labels:
    deepsparse: model
spec:
  replicas: 1
  selector:
    matchLabels:
      deepsparse: model
  template:
    metadata:
      labels:
        deepsparse: model
    spec:
      containers:
      - name: llama-cpp-container
        image: 3x3cut0r/llama-cpp-python:latest
        ports:
        - containerPort: 8000
        env:
        - name: MODEL
          value: "/model/llama-2-7b-chat.Q2_K.gguf"
        #imagePullPolicy: Always
        command: ["sh", "-c"]
        args:
        - |
          pip install huggingface_hub
          python -c 'from huggingface_hub import hf_hub_download
          hf_hub_download(repo_id="TheBloke/Llama-2-7B-Chat-GGUF", filename="llama-2-7b-chat.Q2_K.gguf", local_dir="/model", local_dir_use_symlinks=False, force_download=True)'
          /docker-entrypoint.sh
          #sleep 120
          #curl -X 'POST' 'http://178.62.13.8:32701/register-api-tool/' -H 'accept: application/json' -H 'Content-Type: application/json' -d '{"service_url": "178.62.13.8:30703", "add_routes": ["/v1/completions/", "/v1/models"]}'
        resources:
          limits:
            cpu: 4
            memory: "12Gi"
            #ephemeral-storage: "$ephemeral_memory"
          requests:
            cpu: 4 # must accommodate num-cores requested for execution
            memory: "12Gi" # must accommodate for the model's weights
            #ephemeral-storage: "$ephemeral_memory"
        volumeMounts:
        - name: benchmarkmodel-storage
          mountPath: "/model"
      restartPolicy: Always
      volumes:
      - name: benchmarkmodel-storage
        persistentVolumeClaim:
          claimName: benchmarkmodel-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: benchmarkmodel
  namespace: demo
spec:
  selector:
    deepsparse: model
  ports:
    - name: https
      port: 8000
      nodePort: 30703
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmarkmodel-pvc
  namespace: demo
spec:
  storageClassName: longhorn-nr
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
    storage: 24Gi