apiVersion: v1
kind: Namespace
metadata:
  name: benchmark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: benchmarkmodel
  namespace: benchmark
  labels:
    llamacpp: model
    model_library: model
spec:
  replicas: 1
  selector:
    matchLabels:
      llamacpp: model
      model_library: model
  template:
    metadata:
      labels:
        llamacpp: model
        model_library: model
    spec:
      containers:
      - name: llama-cpp-container
        image: 3x3cut0r/llama-cpp-python:latest
        ports:
        - containerPort: 8000
        env:
        - name: MODEL
          value: "/model/llama-2-7b-chat.Q2_K.gguf"
        #imagePullPolicy: Always
        command: ["sh", "-c"]
        args:
        - |
          pip install huggingface_hub
          python -c 'from huggingface_hub import hf_hub_download
          hf_hub_download(repo_id="TheBloke/Llama-2-7B-Chat-GGUF", filename="llama-2-7b-chat.Q2_K.gguf", local_dir="/model", local_dir_use_symlinks=False, force_download=True)'
          /docker-entrypoint.sh
        resources:
          limits:
            cpu: 4
            memory: "12Gi"
            
          requests:
            cpu: 4 # must accommodate num-cores requested for execution
            memory: "12Gi" # must accommodate for the model's weights
            
        volumeMounts:
        - name: benchmarkmodel-storage
          mountPath: "/model"
      restartPolicy: Always
      volumes:
      - name: benchmarkmodel-storage
        persistentVolumeClaim:
          claimName: benchmarkmodel-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: benchmarkmodel
  namespace: benchmark
spec:
  selector:
    llamacpp: model
    model_library: model
  ports:
    - name: https
      port: 8000
      #nodePort: 30543
      protocol: TCP
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmarkmodel-pvc
  namespace: benchmark
spec:
  storageClassName: longhorn-nr
  accessModes:
   - ReadWriteOnce
  resources:
   requests:
    storage: 24Gi