apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: adam
  name: chat-ui-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-ui-app
  template:
    metadata:
      labels:
        app: chat-ui-app
    spec:
      containers:
      - name: chat-ui-container
        image: python:3.11-slim
        ports:
        - containerPort: 8000
        env:
        - name: LLM_API_KEY
          value: "None"
        - name: LLM_MODEL
          value: "phi-2"
        - name: LLM_BASE_URL
          value: "http://178.62.13.8:31095"
        - name: RETRIEVER_BASE_URL
          value: "http://178.62.13.8:31645"
        - name: RETRIEVER_API_KEY
          value: "None"
        - name: CHAT_USE_AUTH
          value: "True"
        - name: USERNAME
          value: "Adam"
        - name: PASSWORD
          value: "kalavai"
        command: ["/bin/sh", "-c"]
        args:
        - |
          apt-get update && apt-get install -y git
          pip install chainlit
          apt-get install -y gettext
          git clone https://github.com/kalavai-net/tool_library.git /app/tool_library
          cd /app/tool_library
          git checkout feature/updates          
          cd tool_library/example_tools/chat_ui
          pip install -r requirements.txt
          sh prepare.sh
          chainlit run chat_ui.py --host 0.0.0.0 --port 8000
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        - name: chat-ui-app-storage
          mountPath: "/tool"
      restartPolicy: Always
      volumes:
      - name: chat-ui-app-storage
---
apiVersion: v1
kind: Service
metadata:
  name: chat-ui-app-service
  namespace: adam
  labels:
    app: chat-ui-app
spec:
  selector:
    app: chat-ui-app
  ports:
    - name: http
      port: 8000
  type: NodePort
