apiVersion: v1
kind: Namespace
metadata:
  name: adam
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: adam
  name: rag-tool-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rag-tool-test
  template:
    metadata:
      labels:
        app: rag-tool-test
    spec:
      containers:
      - name: rag-tool-container
        image: python:3.8-slim
        ports:
        - containerPort: 8000
        env:
        - name: RAG_USE_AUTH
          value: "False"
        - name: RAG_MASTER_KEY
          value: ""
        command: ["/bin/sh", "-c"]
        args:
        - |
          apt-get update && apt-get install -y git
          git clone https://github.com/kalavai-net/tool_library.git /app/tool_library
          cd /app/tool_library
          git checkout feature/updates
          pip install fastapi uvicorn
          cd tool_library/example_tools/rag
          pip install -r requirements.txt
          uvicorn api:app --host 0.0.0.0 --port 8000
        resources:
          limits:
            cpu: 2
            memory: 4Gi
          requests:
            cpu: 2
            memory: 4Gi
        volumeMounts:
        - name: rag-tool-test-volume
          mountPath: "/tool"
      restartPolicy: Always
      volumes:
      - name: rag-tool-test-volume
---
apiVersion: v1
kind: Service
metadata:
  name: rag-tool-test-service
  namespace: adam
  labels:
    app: rag-tool-test
spec:
  selector:
    app: rag-tool-test
  ports:
    - name: http
      port: 8000
  type: NodePort
